window.KADAPA_SCENES = [
  {id:'c1-s1',chapter:1,bg:'patha-home',speaker:'Narrator',text:'Patha Kadapa wakes with temple bells and bike horns. Yagnesh folds his intermediate notes, pretending he is calm. He is absolutely not calm.',effects:{time:'morning'},choices:[{label:'Breathe and act normal',next:'c1-s2',delta:{affection:1,energy:2}}]},
  {id:'c1-s2',chapter:1,bg:'gd-house',speaker:'GD',text:'"Operation Line-of-Sight begins. Petrol is expensive, romance is free, and your face is already panicking." Lokesh salutes with a biscuit.',choices:[{label:'Accept mission briefing',next:'c1-s3',delta:{humor:2}},{label:'Ask for stealth plan',next:'c1-s3',delta:{logic:2}}]},
  {id:'c1-s3',chapter:1,bg:'college-hall',speaker:'Narrator',text:'10:30 AM break. Super Chaina empties into the corridor. N120 and N120-Apex stare at each other like rival kingdoms. Yagnesh parks at N120 door with GD and Lokesh.',choices:[{label:'Peek casually toward Apex',next:'c1-s4',delta:{affection:2,blush:1}},{label:'Act cool and listen to GD roast seniors',next:'c1-s4',delta:{humor:1}}]},
  {id:'c1-s4',chapter:1,bg:'college-hall',speaker:'Apex Friend',text:'"Look, Yogitha… your bodyguard is on duty again." They stand in a human wall, blocking the doorway while Yogitha hides a smile.',choices:[{label:'Deploy Lokesh distraction',next:'c1-s5',delta:{logic:1,humor:2}},{label:'Ask GD for reflection-angle trick',next:'c1-s6',delta:{logic:3}}]},
  {id:'c1-s5',chapter:1,bg:'college-hall',speaker:'Lokesh',text:'"Emergency announcement! Who stole my imaginary tiffin?" Half the corridor turns. One-second gap. Yagnesh sees Yogitha blush and tuck hair behind ear.',choices:[{label:'Hold eye contact for one heartbeat',next:'c1-s7',delta:{affection:3,blush:2}}]},
  {id:'c1-s6',chapter:1,bg:'college-hall',speaker:'GD',text:'GD points at a dusty window. "Angle in equals angle out. Physics for lovers." Yagnesh checks reflection, but locks eyes with an angry lecturer instead.',choices:[{label:'Apologize and retreat',next:'c1-s7',delta:{humor:2,energy:-1}}]},
  {id:'c1-s7',chapter:1,bg:'college-lunch',speaker:'Narrator',text:'12:50 PM lunch. Long corridor gossip, steel lunch boxes, and hidden glances. Yogitha passes with friends; they tease, she blushes, and keeps walking slower than usual.',choices:[{label:'Smile softly, no words',next:'c1-s8',delta:{affection:2}},{label:'Look away shyly',next:'c1-s8',delta:{blush:1}}]},
  {id:'c1-s8',chapter:1,bg:'road-evening',speaker:'Narrator',text:'4:30 PM evening break. Final window before autos leave. Yagnesh tracks the yellow auto like it is moonrise over Kadapa.',choices:[{label:'Start Shadow Follow mini-game',next:'mg-follow-1',miniGame:'shadow-follow'}]},

  {id:'c2-s1',chapter:2,bg:'road-rain',speaker:'Narrator',text:'Monsoon crashes into Kadapa. GD drives through puddles, shouting about clutch, chain, and ruined hairstyle while Yagnesh searches the auto ahead.',choices:[{label:'Cover with umbrella and continue',next:'c2-s2',delta:{affection:4,energy:-1}},{label:'Stop to wipe mirrors first',next:'c2-s2',delta:{logic:2}}]},
  {id:'c2-s2',chapter:2,bg:'road-rain',speaker:'GD',text:'"If this bike slips, your love story becomes orthopedics." Yogitha peeks from her dry auto and giggles watching both boys shiver dramatically.',choices:[{label:'Wave awkwardly',next:'c2-s3',delta:{blush:3}},{label:'Pretend heroic silence',next:'c2-s3',delta:{affection:2}}]},
  {id:'c2-s3',chapter:2,bg:'strike-day',speaker:'Narrator',text:'Auto strike day. Yogitha and friends walk toward Shanthi Nagar. GD crawls the bike at 5 km/h as "security escort" and complains he is burning clutch plates for romance.',choices:[{label:'Guard from distance',next:'c2-s4',delta:{affection:4,logic:1}},{label:'Ride ahead and wait at turns',next:'c2-s4',delta:{logic:2}}]},
  {id:'c2-s4',chapter:2,bg:'shanthi-street',speaker:'Apex Friend',text:'"Still here? Unbelievable." They glare. Yogitha looks down, smiling anyway. Her steps slow whenever Yagnesh slows.',choices:[{label:'Keep respectful distance',next:'c2-s5',delta:{affection:3}},{label:'Ask Lokesh for comic cover',next:'c2-s5',delta:{humor:2}}]},
  {id:'c2-s5',chapter:2,bg:'sankranti',speaker:'Narrator',text:'Sankranti evening. Traditional wear, rangoli lights, and relatives everywhere. Yagnesh and Yogitha accidentally cross paths near sugarcane stalls.',choices:[{label:'Nod with folded hands',next:'c2-s6',delta:{affection:3,blush:3}},{label:'Step aside to avoid aunties',next:'c2-s6',delta:{humor:2}}]},
  {id:'c2-s6',chapter:2,bg:'gd-house-night',speaker:'GD',text:'At the strategy hub, GD updates a hand-drawn "Blush Probability Chart." Lokesh adds stickers. "Brother, destiny is stable. Only style varies," GD concludes.',choices:[{label:'Plan tomorrow route',next:'c2-s7',delta:{logic:2}},{label:'Replay festival moment in silence',next:'c2-s7',delta:{affection:2}}]},
  {id:'c2-s7',chapter:2,bg:'college-hall',speaker:'Narrator',text:'Weeks pass in corridor warfare: blocked views, accidental glances, and tiny smiles that feel like full songs.',choices:[{label:'Continue steady routine',next:'c3-s1',delta:{affection:4}}]},

  {id:'c3-s1',chapter:3,bg:'exam-day',speaker:'Narrator',text:'Pre-board stress. Even then, 10:30 break remains sacred. Yagnesh reaches N120 door; Yogitha is already aware and pretends not to be.',choices:[{label:'Send luck through eye contact',next:'c3-s2',delta:{affection:2}},{label:'Stay hidden behind GD',next:'c3-s2',delta:{blush:1}}]},
  {id:'c3-s2',chapter:3,bg:'farewell-hall',speaker:'Narrator',text:'12th farewell decorations shimmer. For the first time, silence feels heavier than fear.',choices:[{label:'Confess honestly',next:'c3-s3',delta:{affection:8,blush:6}},{label:'Start with apology for awkward days',next:'c3-s3',delta:{affection:6,logic:1}}]},
  {id:'c3-s3',chapter:3,bg:'farewell-hall',speaker:'Yogitha',text:'"I noticed everything. The rain, the waiting, the way you never crossed limits." She smiles. "Yes, Yagnesh."',choices:[{label:'Breathe. Smile. Thank her.',next:'c3-s4',delta:{affection:10,blush:8}}]},
  {id:'c3-s4',chapter:3,bg:'college-gate-evening',speaker:'GD',text:'"Accepted! Finally I can stop funding this surveillance romance." Lokesh dances with a samosa as if it is a trophy.',choices:[{label:'Celebrate with chai',next:'c4-s1',delta:{humor:3,energy:2}}]},

  {id:'c4-s1',chapter:4,bg:'new-rtc-road',speaker:'Narrator',text:'Post-confession era unlocks New RTC Road. First official date: bangles, bookstores, and nervous smiles.',choices:[{label:'Choose blue bangles she glances at',next:'c4-s2',delta:{affection:5,blush:2}},{label:'Ask her to pick what she likes',next:'c4-s2',delta:{affection:4,logic:1}}]},
  {id:'c4-s2',chapter:4,bg:'yv-street',speaker:'Lokesh',text:'"Relative alert at 2 o clock!" Boys form a comic human shield while Yagnesh and Yogitha share pani puri laughter.',choices:[{label:'Thank wingmen',next:'c4-s3',delta:{humor:3}},{label:'Escape via side lane',next:'c4-s3',delta:{logic:2}}]},
  {id:'c4-s3',chapter:4,bg:'lake-evening',speaker:'Narrator',text:'Dating months flow gently: study sessions, temple visits, tiny fights resolved in minutes, and countless blushes.',choices:[{label:'Promise lifelong respect',next:'c5-s1',delta:{affection:6}}]},

  {id:'c5-s1',chapter:5,bg:'pelli-prep',speaker:'Narrator',text:'Families agree. The wedding mandapam glows with marigold and silk. Nadaswaram rises like dawn.',choices:[{label:'Start Jeelakarra Bellam mini-game',next:'mg-jeelakarra',miniGame:'jeelakarra'}]},
  {id:'c5-s2',chapter:5,bg:'pelli-stage',speaker:'Narrator',text:'Jeelakarra Bellam completes perfectly; the hall cheers. Yogitha’s eyes hold steady, warm, and fearless.',choices:[{label:'Begin Talambralu mini-game',next:'mg-talambralu',miniGame:'talambralu'}]},
  {id:'c5-s3',chapter:5,bg:'pelli-stage',speaker:'Yogitha',text:'Rice rain, laughter, and golden lights. "From corridor glances to this... destiny had patience," she whispers.',choices:[{label:'Tie the knot with gratitude',next:'c6-s1',delta:{affection:10,blush:6}}]},

  {id:'c6-s1',chapter:6,bg:'patha-home-new',speaker:'Narrator',text:'Newlywed life starts with sunrise chai, rain on tiled roofs, and long scooter rides through Kadapa lanes.',choices:[{label:'Build routines together',next:'c6-s2',delta:{affection:4,energy:2}}]},
  {id:'c6-s2',chapter:6,bg:'gd-house-night',speaker:'GD',text:'GD hangs a framed photo labeled "Operation Successful." Lokesh still claims credit for imaginary tiffin distraction.',choices:[{label:'Laugh and relive old missions',next:'c7-s1',delta:{humor:4}}]},

  {id:'c7-s1',chapter:7,bg:'new-rtc-road',speaker:'Narrator',text:'Arc 7 opens with a couple date-night montage: cinema queues, roadside chai, and shared umbrella walks.',choices:[{label:'Choose window seat theater',next:'c7-s2',delta:{blush:2}},{label:'Choose street-food walk',next:'c7-s2',delta:{affection:3}}]},
  {id:'c7-s2',chapter:7,bg:'yv-street',speaker:'Yogitha',text:'"Back then I blushed in silence. Now I can laugh loudly with you," she says, offering extra pani puri.',choices:[{label:'Tease her about old corridor glances',next:'c7-s3',delta:{humor:3}},{label:'Thank her for trusting destiny',next:'c7-s3',delta:{affection:3}}]},
  {id:'c7-s3',chapter:7,bg:'lake-evening',speaker:'Narrator',text:'The affection bar nears full as trust, respect, and friendship stabilize into daily joy.',choices:[{label:'Advance to family-building arc',next:'c8-s1',delta:{affection:4,blush:1}}]},

  {id:'c8-s1',chapter:8,bg:'patha-home-new',speaker:'Narrator',text:'Festival season returns. This time, both stand together in traditional wear with no hiding, no fear.',choices:[{label:'Host Sankranti at home',next:'c8-s2',delta:{energy:3,affection:3}},{label:'Visit Shanthi Nagar relatives',next:'c8-s2',delta:{logic:2}}]},
  {id:'c8-s2',chapter:8,bg:'sankranti',speaker:'Apex Friend',text:'Even old blockers now grin and mutter, "Fine, this was inevitable." Yogitha laughs at their surrender.',choices:[{label:'Accept playful teasing',next:'c8-s3',delta:{humor:2,blush:2}}]},
  {id:'c8-s3',chapter:8,bg:'gd-house',speaker:'Lokesh',text:'"From bodyguard to husband arc complete!" GD pretends to invoice petrol for all previous years.',choices:[{label:'Pay him in biryani',next:'c9-s1',delta:{humor:3}}]},

  {id:'c9-s1',chapter:9,bg:'college-hall',speaker:'Narrator',text:'Memory chapter: a return visit near Narayana campus. Corridors are quieter, but echoes of old breaks remain.',choices:[{label:'Recreate 10:30 break pose',next:'c9-s2',delta:{affection:2}},{label:'Take photos at N120 doorway',next:'c9-s2',delta:{blush:2}}]},
  {id:'c9-s2',chapter:9,bg:'college-gate-evening',speaker:'Yogitha',text:'"You never crossed limits, and that made all the difference." Her line locks affection into permanence.',choices:[{label:'Hold her hand and smile',next:'c9-s3',delta:{affection:5}}]},
  {id:'c9-s3',chapter:9,bg:'road-evening',speaker:'Narrator',text:'A passing auto triggers both to laugh instantly—some symbols stay forever.',choices:[{label:'Continue to legacy arc',next:'c10-s1',delta:{humor:2,energy:2}}]},

  {id:'c10-s1',chapter:10,bg:'patha-home-new',speaker:'Narrator',text:'Career and home balance chapter: budgeting, weekend planning, and emotional check-ins become elegant habits.',choices:[{label:'Prioritize quality time',next:'c10-s2',delta:{affection:4}},{label:'Optimize weekly schedules',next:'c10-s2',delta:{logic:3}}]},
  {id:'c10-s2',chapter:10,bg:'new-rtc-road',speaker:'GD',text:'"Romance with spreadsheets—approved," GD says, while Lokesh decorates the planner with cartoon hearts.',choices:[{label:'Promote them to official advisors',next:'c10-s3',delta:{humor:3}}]},
  {id:'c10-s3',chapter:10,bg:'lake-evening',speaker:'Narrator',text:'Blush meter stabilizes high whenever private compliments meet public respect.',choices:[{label:'Move into celebration chapters',next:'c11-s1',delta:{blush:4}}]},

  {id:'c11-s1',chapter:11,bg:'pelli-stage',speaker:'Narrator',text:'Anniversary celebration recreates wedding visuals: marigold curtains, veena motifs, and warm nadaswaram loops.',choices:[{label:'Exchange vows again',next:'c11-s2',delta:{affection:5,blush:3}}]},
  {id:'c11-s2',chapter:11,bg:'pelli-stage',speaker:'Yogitha',text:'"Destiny chose the ending. We chose the tone—funny, gentle, and ours."',choices:[{label:'Seal chapter with gratitude',next:'c11-s3',delta:{affection:5}}]},
  {id:'c11-s3',chapter:11,bg:'credits',speaker:'Narrator',text:'Your build now approaches full stats. Final chapter unlocks detailed debug summary.',choices:[{label:'Enter Chapter 12 Finale',next:'c12-s1'}]},

  {id:'c12-s1',chapter:12,bg:'credits',speaker:'Narrator',text:'Grand Finale. All arcs converge: school crush, auto follows, confession, marriage, and long-term harmony.',choices:[{label:'Run final state audit',next:'c12-s2',delta:{affection:8,blush:8,energy:4}}]},
  {id:'c12-s2',chapter:12,bg:'credits',speaker:'Narrator',text:'DEBUG NOTE: affection & blush are designed to fully cap by late Chapter 11 or during Chapter 12 decision bonus. Destiny-Fixed confirmed across all paths.',choices:[{label:'View ending stats',next:null}]}
];
