window.KADAPA_SCENES = [
  // Chapter 1 - 11th Class: First Patterns
  { id:'c1-s1', chapter:1, bg:'patha-home-dawn', speaker:'Narrator', text:'Patha Kadapa wakes in soft orange light. Pressure-cooker whistles, temple bells, and bike horns blend into morning rhythm. Yagnesh checks his bag twice, combs his hair three times, and still feels unprepared for one ordinary school day that is not ordinary to him. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', effects:{time:'morning'}, choices:[{label:'Walk to GD house first', next:'c1-s2', delta:{logic:1}},{label:'Go straight to college gate', next:'c1-s2', delta:{energy:1}}] },
  { id:'c1-s2', chapter:1, bg:'gd-house-courtyard', speaker:'GD', text:'GD starts briefing like a battlefield commander: "Respect first, distance first, dignity first. Romance without manners is nonsense." Lokesh interrupts with a salute and biscuit. The mission is simple: survive breaks without panicking. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Accept mission rules', next:'c1-s3', delta:{logic:2}},{label:'Ask Lokesh for confidence joke', next:'c1-s3', delta:{humor:2}}] },
  { id:'c1-s3', chapter:1, bg:'college-corridor-am', speaker:'Narrator', text:'10:30 AM break at Narayana. Super Chaina releases students into the corridor. N120 and N120-Apex face each other across the hall like two worlds holding breath. Yogitha enters Apex; her friends immediately notice Yagnesh at N120 door. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Stay calm and stand naturally', next:'c1-s4', delta:{affection:2}},{label:'Hide behind GD and peek once', next:'c1-s4', delta:{blush:2}}] },
  { id:'c1-s4', chapter:1, bg:'college-corridor-am', speaker:'Apex Friend', text:'"Bodyguard shift started again," one friend says, blocking line of sight. Yogitha looks away but her smile almost escapes. Lokesh whispers, "Line-of-sight war phase one." The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Deploy Lokesh distraction', next:'c1-s5', delta:{humor:2}},{label:'Use GD reflection angle', next:'c1-s5', delta:{logic:2}}] },
  { id:'c1-s5', chapter:1, bg:'college-lunch', speaker:'Narrator', text:'Lunch break. Steel boxes open, corridor gossip rises, and tiny glances travel between doorways. Yagnesh never crosses boundaries, never talks over her space. Yogitha notices that restraint. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'End day quietly', next:'c2-s1', delta:{affection:2,energy:1}}] },

  // Chapter 2 - 11th Class: Rain and Route Tracking
  { id:'c2-s1', chapter:2, bg:'college-gate-evening', speaker:'Narrator', text:'4:30 PM, final break. Autos line up outside gate. GD checks mirrors and says, "Safe distance only." Yogitha boards her auto with friends. The chase begins. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Start Shadow Follow', next:'mg-follow-1', miniGame:'shadow-follow'}] },
  { id:'c2-s2', chapter:2, bg:'road-rain', speaker:'Narrator', text:'Rain crashes over Kadapa roads. GD drives through puddles while complaining about mud, chain noise, and emotional damage to bike paint. Yogitha glances back from dry auto and quietly laughs. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Continue steadily in rain', next:'c2-s3', delta:{affection:4,energy:-1}},{label:'Pause briefly then resume', next:'c2-s3', delta:{logic:2}}] },
  { id:'c2-s3', chapter:2, bg:'shanthi-road-strike', speaker:'Narrator', text:'Auto strike day. Yogitha must walk far toward Shanthi Nagar. GD moves bike at 5 km/h as security escort and keeps muttering about clutch plate sacrifice for love. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Guard from behind at distance', next:'c2-s4', delta:{affection:3,logic:1}},{label:'Scout turns and wait ahead', next:'c2-s4', delta:{logic:2}}] },
  { id:'c2-s4', chapter:2, bg:'shanthi-street', speaker:'Apex Friend', text:'Her friends glare, tease, and still block. Yogitha acts strict, but her walking speed syncs with Yagnesh at turns. Safety starts feeling like trust. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Keep respectful silence', next:'c2-s5', delta:{affection:3}},{label:'Ask Lokesh to lighten tension', next:'c2-s5', delta:{humor:2}}] },
  { id:'c2-s5', chapter:2, bg:'gd-house-night', speaker:'GD', text:'Night debrief at GD house: route map, break timings, and absurd probability chart for smile events. Everyone laughs, but the system works. Slow progress, no drama, steady respect. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Carry routine into next month', next:'c3-s1', delta:{logic:1,affection:2}}] },

  // Chapter 3 - 11th Class: Festival and Confidence
  { id:'c3-s1', chapter:3, bg:'sankranti-bazaar', speaker:'Narrator', text:'Sankranti evening fills streets with rangoli, kites, sugarcane carts, and relatives. Yagnesh and Yogitha cross paths in traditional wear. One second of eye contact feels like a full song. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Fold hands and smile', next:'c3-s2', delta:{blush:3,affection:2}},{label:'Step aside politely', next:'c3-s2', delta:{logic:1,affection:1}}] },
  { id:'c3-s2', chapter:3, bg:'college-corridor-pm', speaker:'Narrator', text:'Back in routine, corridor war continues: block, tease, glance, retreat. But hostility softens into ritual. Yogitha is no longer surprised to find Yagnesh at the same respectful distance every break. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Stay consistent', next:'c3-s3', delta:{affection:2}},{label:'Focus on marks + routine', next:'c3-s3', delta:{energy:2,logic:1}}] },
  { id:'c3-s3', chapter:3, bg:'classroom-window-rain', speaker:'Narrator', text:'A rainy day traps everyone inside classrooms. A pen falls near corridor edge. Yagnesh picks it up, places it near Yogitha desk, returns without a word. She whispers thanks. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Nod and leave', next:'c3-s4', delta:{affection:3,blush:1}}] },
  { id:'c3-s4', chapter:3, bg:'gd-house-terrace', speaker:'Lokesh', text:'On terrace under cloudy sky, Lokesh says, "Brother, she already knows. Now pass exams and don’t become poetry disaster." GD agrees with unusual softness. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Promise discipline', next:'c3-s5', delta:{logic:2}},{label:'Promise patience', next:'c3-s5', delta:{affection:2}}] },
  { id:'c3-s5', chapter:3, bg:'patha-night-sky', speaker:'Narrator', text:'11th class closes with no confession, no shortcuts, and no regret. The foundation is built: safety, consistency, and quiet humor. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Advance to Chapter 4 (12th begins)', next:'c4-s1', delta:{energy:2}}] },

  // Chapter 4 - 12th Class: Pressure + Growth
  { id:'c4-s1', chapter:4, bg:'exam-hall-morning', speaker:'Narrator', text:'12th class starts with pressure, timetable walls, and parents asking rank predictions every Sunday. Even now, 10:30 break remains sacred. Same corridor. Same heartbeat. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Send silent good-luck glance', next:'c4-s2', delta:{affection:2}},{label:'Stay focused and avoid looking', next:'c4-s2', delta:{logic:2}}] },
  { id:'c4-s2', chapter:4, bg:'college-lunch-court', speaker:'GD', text:'GD manages tactical nonsense and emotional stability simultaneously. "No heroic mistakes before boards," he says. "And drink water. Romance dehydration is real." The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Follow GD protocol', next:'c4-s3', delta:{energy:2,logic:1}},{label:'Ask Lokesh for stress relief', next:'c4-s3', delta:{humor:2}}] },
  { id:'c4-s3', chapter:4, bg:'road-evening-trees', speaker:'Narrator', text:'Evening auto follow is now less chase and more routine assurance. The auto driver never suspects anything; to him, this is just three local boys returning home by same route daily. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Maintain exact safe distance', next:'c4-s4', delta:{logic:2,affection:1}},{label:'Use casual cover at signals', next:'c4-s4', delta:{humor:2}}] },
  { id:'c4-s4', chapter:4, bg:'shanthi-main-road', speaker:'Narrator', text:'One stressful day, relatives pass near the lane. Everyone freezes. GD improvises a fake bike issue; Lokesh asks random directions. Yogitha suppresses laughter and walks on. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Recover calmly', next:'c4-s5', delta:{affection:2,energy:-1}},{label:'Debrief and improve plan', next:'c4-s5', delta:{logic:2}}] },
  { id:'c4-s5', chapter:4, bg:'study-night-lamp', speaker:'Narrator', text:'Months pass. Between exams and rain and corridor comedy, feelings mature. The question is no longer "does she know?" but "when is the right time?" The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Move to mid-12th turning point', next:'c5-s1', delta:{affection:2}}] },

  // Chapter 5 - 12th Mid: Acceptance
  { id:'c5-s1', chapter:5, bg:'farewell-decor-hall', speaker:'Narrator', text:'Mid-12th cultural day and farewell prep bring emotions to surface. Banners, signatures, loud jokes hiding real fear of endings. GD and Lokesh stand guard near side corridor like loyal generals. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Confess honestly', next:'c5-s2', delta:{affection:6,blush:4}},{label:'Start with apology and respect', next:'c5-s2', delta:{affection:5,logic:1}}] },
  { id:'c5-s2', chapter:5, bg:'farewell-corridor-gold', speaker:'Yogitha', text:'"I noticed everything," Yogitha says softly. "Rain rides, strike day, and how you never crossed limits. I needed time. I like you too." For a second, corridor noise disappears. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Thank her with calm promise', next:'c5-s3', delta:{affection:8,blush:5}}] },
  { id:'c5-s3', chapter:5, bg:'college-gate-sunset', speaker:'Narrator', text:'Acceptance changes tone, not values. No flashy stunt. No rushing. Just relief, gratitude, and awkward happy laughter with friends pretending not to cry. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Begin slow talking phase', next:'c5-s4', delta:{energy:2,humor:2}}] },
  { id:'c5-s4', chapter:5, bg:'phone-call-night', speaker:'Narrator', text:'First regular calls begin—short, shy, careful. Marks, teachers, family expectations, favorite songs, and silent pauses that still feel full. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Keep conversations gentle', next:'c5-s5', delta:{affection:3,blush:2}},{label:'Keep conversations practical', next:'c5-s5', delta:{logic:2,affection:1}}] },
  { id:'c5-s5', chapter:5, bg:'patha-dawn-road', speaker:'Narrator', text:'12th mid chapter locks the relationship status: accepted. The rest is about growing from school affection into adult partnership. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Enter final 12th stretch', next:'c6-s1', delta:{affection:2}}] },

  // Chapter 6 - 12th End: Transition to BTech
  { id:'c6-s1', chapter:6, bg:'exam-season-city', speaker:'Narrator', text:'Board exams arrive like a storm front. Calls become shorter but warmer: "Did you eat?" "Sleep early." "All the best." Love learns discipline. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Prioritize studies with trust', next:'c6-s2', delta:{logic:3,affection:2}},{label:'Balance study and emotional support', next:'c6-s2', delta:{energy:2,affection:3}}] },
  { id:'c6-s2', chapter:6, bg:'results-day-crowd', speaker:'Narrator', text:'Results day brings panic, relief, and group selfies. Both families begin discussing college admissions. Future gets real and slightly scary. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Choose confidence', next:'c6-s3', delta:{energy:2}},{label:'Choose planning', next:'c6-s3', delta:{logic:2}}] },
  { id:'c6-s3', chapter:6, bg:'gd-house-strategy', speaker:'GD', text:'GD announces Phase-2 protocol: "BTech era: more talking, less stalking. Upgrade maturity firmware immediately." Lokesh claps like product launch host. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Accept BTech maturity upgrade', next:'c6-s4', delta:{logic:2,humor:1}}] },
  { id:'c6-s4', chapter:6, bg:'bus-stand-evening', speaker:'Narrator', text:'Different colleges, different schedules, same city sky. Distance introduces stress, but also richer conversations beyond corridor glances. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Commit to communication routine', next:'c6-s5', delta:{affection:3,logic:2}},{label:'Commit to weekly meetups', next:'c6-s5', delta:{affection:3,energy:1}}] },
  { id:'c6-s5', chapter:6, bg:'chapter-gate-blue', speaker:'Narrator', text:'12th closes with acceptance intact and trust stronger than before. Next arc begins: BTech dating, deeper talks, real-world complexity. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Enter BTech Arc', next:'c7-s1', delta:{affection:2}}] },

  // Chapter 7 - BTech Year 1-2: Dating Opens
  { id:'c7-s1', chapter:7, bg:'new-rtc-road-evening', speaker:'Narrator', text:'BTech begins. New RTC Road unlocks properly for dates: bookstores, theaters, chai points, and safe corners for long conversations. GD and Lokesh now act as comic logistics team, not corridor tacticians. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Plan a movie date', next:'c7-s2', delta:{blush:2}},{label:'Plan bookshop + tea date', next:'c7-s2', delta:{affection:2,logic:1}}] },
  { id:'c7-s2', chapter:7, bg:'theater-lobby', speaker:'Yogitha', text:'In the theater queue, Yogitha laughs: "Your team still behaves like secret agents." Yagnesh admits he is more scared of random relatives than semester exams. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Laugh and keep it playful', next:'c7-s3', delta:{humor:3}},{label:'Share sincere appreciation', next:'c7-s3', delta:{affection:3}}] },
  { id:'c7-s3', chapter:7, bg:'yv-street-night', speaker:'Narrator', text:'YV Street date: pani puri, roasted corn, and long talks about careers, values, and family. Their love shifts from excitement to compatibility. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Discuss future goals deeply', next:'c7-s4', delta:{logic:3,affection:2}},{label:'Keep date light and joyful', next:'c7-s4', delta:{energy:2,humor:2}}] },
  { id:'c7-s4', chapter:7, bg:'rainy-bus-shelter', speaker:'Narrator', text:'A sudden rain forces shelter. Old memories return instantly. What was once shy surveillance is now shared nostalgia and open laughter. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Promise consistency through all years', next:'c7-s5', delta:{affection:4,blush:2}}] },
  { id:'c7-s5', chapter:7, bg:'btech-campus-walk', speaker:'Narrator', text:'Year 1 and 2 pass with gentle rhythm: classes, assignments, calls, and weekend meetups. No dramatic breakup arcs exist; only tone differences and growth speed. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Advance to deeper BTech phase', next:'c8-s1', delta:{affection:2}}] },

  // Chapter 8 - BTech Year 3: Mini-game + Complex Talks
  { id:'c8-s1', chapter:8, bg:'city-traffic-night', speaker:'Narrator', text:'Third-year schedules get heavy. Stress rises with internships and deadlines. Still, some evenings replay the old pattern: auto routes, bike rides, and coded jokes about mission history. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Start nostalgic Shadow Follow challenge', next:'mg-follow-2', miniGame:'shadow-follow'}] },
  { id:'c8-s2', chapter:8, bg:'coffee-shop-study', speaker:'Narrator', text:'They meet in a small cafe to discuss internships, finances, and expectations after graduation. Conversation is complex, mature, and occasionally tense. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Prioritize emotional support', next:'c8-s3', delta:{affection:3,energy:1}},{label:'Prioritize practical planning', next:'c8-s3', delta:{logic:3}}] },
  { id:'c8-s3', chapter:8, bg:'college-fest-stage', speaker:'Narrator', text:'College fest night brings lights and music. Yogitha cheers for Yagnesh from crowd. He finally performs without panic because she is there. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Dedicate performance silently', next:'c8-s4', delta:{blush:3,affection:2}}] },
  { id:'c8-s4', chapter:8, bg:'park-bench-late', speaker:'Yogitha', text:'"We started with glances. Now we can discuss hard things without fear," she says. "That is real love." The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Agree and commit long-term', next:'c8-s5', delta:{affection:4,logic:2}}] },
  { id:'c8-s5', chapter:8, bg:'gd-house-poster', speaker:'GD', text:'GD unveils a ridiculous formula: Respect × Consistency + Humor ÷ Stress = Marriage Probability 100%. Everybody laughs, then quietly agrees. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Archive formula and move on', next:'c9-s1', delta:{humor:3,affection:2}}] },

  // Chapter 9 - BTech Year 4: Decision and Family Talks
  { id:'c9-s1', chapter:9, bg:'placement-cell', speaker:'Narrator', text:'Final-year placement season creates pressure. Success and uncertainty coexist. They support each other without comparison or ego. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Celebrate small wins together', next:'c9-s2', delta:{affection:3}},{label:'Plan fallback routes together', next:'c9-s2', delta:{logic:3}}] },
  { id:'c9-s2', chapter:9, bg:'family-living-room', speaker:'Narrator', text:'Post-placement, families begin serious conversations. Questions come fast: timeline, careers, location, responsibilities. The tone is respectful but intense. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Respond calmly with clarity', next:'c9-s3', delta:{logic:3,energy:1}},{label:'Respond warmly with patience', next:'c9-s3', delta:{affection:3}}] },
  { id:'c9-s3', chapter:9, bg:'temple-street-evening', speaker:'Narrator', text:'A temple visit after difficult discussions restores calm. They choose partnership over panic and process over drama. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Take blessing and continue', next:'c9-s4', delta:{affection:2,blush:1}}] },
  { id:'c9-s4', chapter:9, bg:'college-gate-memory', speaker:'Yogitha', text:'At old college gate, Yogitha says the line that defines everything: "You never crossed my comfort. That is why I trusted you." The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Hold this as life principle', next:'c9-s5', delta:{affection:5,logic:1}}] },
  { id:'c9-s5', chapter:9, bg:'chapter-gate-dusk', speaker:'Narrator', text:'BTech arc closes with acceptance from both hearts and growing family agreement. Next phase: after BTech marriage. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Enter post-BTech wedding arc', next:'c10-s1', delta:{energy:2}}] },

  // Chapter 10 - After BTech: Wedding Preparation
  { id:'c10-s1', chapter:10, bg:'family-meeting-day', speaker:'Narrator', text:'After BTech, timelines align. Wedding discussions become real schedules: hall booking, invitations, shopping runs, elders coordination. Joy and stress move together. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Help with planning sheets', next:'c10-s2', delta:{logic:3}},{label:'Help with decor/music moodboards', next:'c10-s2', delta:{humor:2,affection:1}}] },
  { id:'c10-s2', chapter:10, bg:'shopping-street-bright', speaker:'Narrator', text:'Shopping days flood city roads with color: silk stores, gold lights, traffic noise, and endless chai breaks. Yogitha looks elegant and grounded; Yagnesh looks stunned every five minutes. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Compliment sincerely', next:'c10-s3', delta:{blush:4,affection:3}},{label:'Stay calm and helpful', next:'c10-s3', delta:{logic:2}}] },
  { id:'c10-s3', chapter:10, bg:'wedding-hall-prep', speaker:'Narrator', text:'Mandapam gets built with marigold, brass lamps, and veena motifs. GD still asks for petrol reimbursement with full seriousness. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Start Jeelakarra mini-game rehearsal', next:'mg-jeelakarra', miniGame:'jeelakarra'}] },
  { id:'c10-s4', chapter:10, bg:'wedding-stage-gold', speaker:'Narrator', text:'Jeelakarra moment lands. Families cheer. Priests call next ritual. Emotional energy rises; everyone smiles through tears. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Begin Talambralu mini-game', next:'mg-talambralu', miniGame:'talambralu'}] },
  { id:'c10-s5', chapter:10, bg:'wedding-stage-laughter', speaker:'Yogitha', text:'Rice showers, laughter, and warm lights. "From corridor days to this stage," Yogitha whispers, "long route, right route." The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Tie knot with gratitude', next:'c11-s1', delta:{affection:10,blush:7}}] },

  // Chapter 11 - Married Life Begins
  { id:'c11-s1', chapter:11, bg:'new-home-morning', speaker:'Narrator', text:'After marriage, life opens into practical romance: bills, breakfast, work calls, evening walks, and quiet support after tiring days. Happiness becomes daily craft. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Build routines together', next:'c11-s2', delta:{affection:3,logic:2}},{label:'Keep spontaneity alive', next:'c11-s2', delta:{humor:2,energy:2}}] },
  { id:'c11-s2', chapter:11, bg:'market-road-day', speaker:'Narrator', text:'Market errands become comedy episodes. GD narrates old mission failures while Lokesh claims all credit. Yogitha laughs at both and drags everyone to tea stall. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Enjoy friends and memory', next:'c11-s3', delta:{humor:3,affection:2}}] },
  { id:'c11-s3', chapter:11, bg:'balcony-rain-night', speaker:'Yogitha', text:'Rain on balcony revives old memories. "Earlier you followed my auto," she smiles, "now I follow your health reminders." Both laugh. Blush meter still rises. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Promise lifelong care', next:'c11-s4', delta:{affection:4,blush:3}}] },
  { id:'c11-s4', chapter:11, bg:'anniversary-lights', speaker:'Narrator', text:'Anniversary celebration recreates wedding colors in softer style. Family, friends, music, gratitude. Affection typically reaches full cap in this window. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Exchange vows again', next:'c11-s5', delta:{affection:5,blush:4}}] },
  { id:'c11-s5', chapter:11, bg:'chapter-gate-light', speaker:'Narrator', text:'All major emotional arcs are complete. Final chapter opens a formal audit: stat math, destiny convergence, and happy-ending verification. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Enter Chapter 12 audit + finale', next:'c12-s1'}] },

  // Chapter 12 - Final Audit and Ending
  { id:'c12-s1', chapter:12, bg:'finale-skyline-dawn', speaker:'Narrator', text:'Final dawn over Kadapa. Rooftops, trees, roads, and temple silhouette hold the full timeline: 11th effort, 12th acceptance, BTech growth, after-BTech marriage. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Run affection audit', next:'c12-s2', delta:{logic:2}}] },
  { id:'c12-s2', chapter:12, bg:'debug-screen', speaker:'Narrator', text:'AFFECTION AUDIT: usually reaches 100 around late Chapter 10 to Chapter 11 depending on tone choices. No branch permits collapse events; only pace changes. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Run blush audit', next:'c12-s3', delta:{logic:2}}] },
  { id:'c12-s3', chapter:12, bg:'debug-screen', speaker:'Narrator', text:'BLUSH AUDIT: spikes at acceptance, rituals, and anniversary scenes. Designed full-cap window is late Chapter 10 through Chapter 11. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Run destiny-fixed audit', next:'c12-s4', delta:{logic:2}}] },
  { id:'c12-s4', chapter:12, bg:'debug-screen', speaker:'Narrator', text:'DESTINY AUDIT: every decision tree is flavor-only (funny, awkward, smooth, practical). All paths converge to marriage and long-term harmony. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Run mini-game audit', next:'c12-s5', delta:{logic:2}}] },
  { id:'c12-s5', chapter:12, bg:'debug-screen', speaker:'Narrator', text:'MINI-GAME AUDIT: Shadow Follow, Jeelakarra, and Talambralu alter stats and tone only; they never create failure endings. Autosave is preserved across transitions. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'Finalize ending', next:'c12-s6', delta:{affection:6,blush:6,energy:3}}] },
  { id:'c12-s6', chapter:12, bg:'finale-mandapam-sunrise', speaker:'Narrator', text:'Yagnesh and Yogitha stand together under morning light. The journey stayed gradual, beautiful, funny, shy, stressful at times, and always hopeful. Destiny fulfilled. Happy ending secured. The sky, buildings, trees, and moving crowd hold the emotion of this moment, and every small choice adds gradual depth while destiny remains stable and hopeful. This cinematic continuity keeps humor, shyness, pressure, and happiness balanced across school, college, and married life with clear emotional progression.', choices:[{label:'View final stats', next:null}] },

  // Mini-game nodes
  { id:'mg-follow-1', chapter:2, bg:'college-gate-evening', speaker:'Narrator', text:'Mini node', miniGame:'shadow-follow', choices:[] },
  { id:'mg-follow-2', chapter:8, bg:'city-traffic-night', speaker:'Narrator', text:'Mini node', miniGame:'shadow-follow', choices:[] },
  { id:'mg-jeelakarra', chapter:10, bg:'wedding-hall-prep', speaker:'Narrator', text:'Mini node', miniGame:'jeelakarra', choices:[] },
  { id:'mg-talambralu', chapter:10, bg:'wedding-stage-gold', speaker:'Narrator', text:'Mini node', miniGame:'talambralu', choices:[] }
];
