window.KADAPA_SCENES = [
  // --- Chapter 1: Silent Crush Setup ---
  { id:'c1-s1', chapter:1, bg:'patha-home-morning', speaker:'Narrator', text:'Dawn spreads over Patha Kadapa in peach and blue. Temple bells mix with pressure-cooker whistles, scooters, and crows arguing on electric wires. Yagnesh irons his uniform twice, rewrites one chemistry answer three times, and still cannot calm his heartbeat. He is not afraid of exams. He is afraid of one glance from across a corridor.', effects:{time:'morning'}, choices:[{ label:'Take a deep breath and leave early', next:'c1-s2', delta:{energy:2,logic:1} },{ label:'Ask GD for emotional backup first', next:'c1-s2', delta:{humor:1,affection:1} }] },
  { id:'c1-s2', chapter:1, bg:'gd-house-yard', speaker:'GD', text:'GD leans on his bike like a movie strategist. "Petrol is my sacrifice, brother. Your job is simple: be decent, be respectful, and do not behave like a villain from low-budget cinema." Lokesh appears with tea and announces Operation Line-of-Sight in a fake military voice. Everyone laughs, then goes quiet when the school bell echoes from far away.', choices:[{ label:'Accept mission rules', next:'c1-s3', delta:{logic:2} },{ label:'Request comedy mode for confidence', next:'c1-s3', delta:{humor:2} }] },
  { id:'c1-s3', chapter:1, bg:'college-corridor-morning', speaker:'Narrator', text:'10:30 AM break at Narayana College. Super Chaina spills into the hall. N120 and N120-Apex stand opposite like mirror worlds with chalk dust in the sunlight. Yagnesh joins GD and Lokesh at the N120 doorway. Yogitha enters Apex with her friends; she does not look directly, yet somehow knows exactly where he is standing.', choices:[{ label:'Stay calm and keep respectful distance', next:'c1-s4', delta:{affection:2} },{ label:'Hide behind GD and peek once', next:'c1-s4', delta:{blush:2} }] },
  { id:'c1-s4', chapter:1, bg:'college-corridor-morning', speaker:'Apex Friend', text:'Two friends slide into the Apex doorway, forming a dramatic human wall. "Look, your bodyguard reported for duty," one teases. Yogitha lowers her eyes but her smile escapes anyway. Lokesh whispers that this is a tactical siege. GD starts sketching impossible viewing angles on the back of a test paper like a battlefield engineer.', choices:[{ label:'Send Lokesh to create harmless distraction', next:'c1-s5', delta:{humor:2,logic:1} },{ label:'Trust GD reflection-angle plan', next:'c1-s6', delta:{logic:3} }] },
  { id:'c1-s5', chapter:1, bg:'college-corridor-morning', speaker:'Lokesh', text:'Lokesh loudly asks who dropped a "secret biryani coupon" near the staircase. Half the corridor turns. For two seconds the doorway opens, and Yagnesh sees Yogitha tuck her hair behind her ear while pretending to scold her friends. It is tiny, silent, and enough to power his entire week.', choices:[{ label:'Hold that memory quietly', next:'c1-s7', delta:{affection:3,blush:1} }] },
  { id:'c1-s6', chapter:1, bg:'college-window-angle', speaker:'GD', text:'"Angle in equals angle out," GD whispers, adjusting Yagnesh by exactly one floor tile. The reflection works perfectly for one second. Then an irritated lecturer appears in the same window and stares directly back. GD coughs, Lokesh salutes, and Yagnesh apologizes to pure air before retreating. Even Yogitha struggles to hide her laughter.', choices:[{ label:'Retreat with dignity', next:'c1-s7', delta:{humor:3,energy:-1} }] },
  { id:'c1-s7', chapter:1, bg:'college-lunch-court', speaker:'Narrator', text:'Lunch break stretches long with steel tiffin sounds, chalk smell, and gossip. Yogitha passes with friends; the teasing grows louder, yet her pace slows near N120 every day. Yagnesh never crosses limits. No gifts, no dramatic stunts, only presence. That steadiness begins to matter more than words in a noisy building.', choices:[{ label:'End day with quiet confidence', next:'c2-s1', delta:{affection:2,energy:1} }] },

  // --- Chapter 2: Routine, Rain, and Strike ---
  { id:'c2-s1', chapter:2, bg:'college-evening-gate', speaker:'Narrator', text:'At 4:30 PM the final break feels like a countdown. Autos line up beyond the gate, yellow roofs glowing in evening sun. GD taps the handlebar and reminds everyone: follow at safe distance, do not panic, do not overtake. Yogitha steps into the auto with friends and glances back once before the vehicle pulls into traffic.', choices:[{ label:'Begin Shadow Follow mini-game', next:'mg-follow-1', miniGame:'shadow-follow' }] },
  { id:'c2-s2', chapter:2, bg:'road-rain-kadapa', speaker:'Narrator', text:'Monsoon arrives with full drama. Roads become mirrors; trees bend; shop awnings drip like waterfalls. GD drives while shouting engineering complaints about muddy chain, slipping brakes, and emotional damage to his hairstyle. Yagnesh is soaked but alert. From inside her dry auto, Yogitha notices the two idiots and covers a bright laugh behind her hand.', choices:[{ label:'Keep chasing with umbrella shield', next:'c2-s3', delta:{affection:4,energy:-2} },{ label:'Pause at tea stall then resume route', next:'c2-s3', delta:{logic:2,energy:1} }] },
  { id:'c2-s3', chapter:2, bg:'auto-strike-road', speaker:'Narrator', text:'Auto strike day changes the map. Yogitha and friends must walk a long stretch toward Shanthi Nagar. GD creeps the bike at five kilometers per hour like a reluctant security vehicle, muttering about clutch plates and destiny taxes. Friends glare; Yagnesh keeps distance. The road is tense, but Yogitha walks calmer knowing someone is quietly watching out.', choices:[{ label:'Stay behind and guard turns', next:'c2-s4', delta:{affection:4,logic:1} },{ label:'Ride ahead and check side lanes', next:'c2-s4', delta:{logic:3} }] },
  { id:'c2-s4', chapter:2, bg:'shanthi-nagar-lane', speaker:'Apex Friend', text:'"Still following? Unbelievable," one friend says, annoyed. Another teases Yogitha: "Your personal convoy is here." Yogitha acts stern, but her eyes soften when Yagnesh slows at the same speed as their group and never crosses into their space. Boundaries hold. Trust grows quietly between irritation, jokes, and evening traffic.', choices:[{ label:'Nod politely and keep distance', next:'c2-s5', delta:{affection:3,blush:2} },{ label:'Signal Lokesh for harmless diversion', next:'c2-s5', delta:{humor:2} }] },
  { id:'c2-s5', chapter:2, bg:'gd-house-night', speaker:'GD', text:'Night debrief at GD’s house: map on wall, snack packets on floor, bike keys in center like sacred relic. GD calculates routes by bell timings, traffic density, and rain probability. Lokesh contributes vibe analytics: "When she slows near gate, confidence plus three." The plan is ridiculous, detailed, and unexpectedly effective.', choices:[{ label:'Update daily routine chart', next:'c2-s6', delta:{logic:2} },{ label:'Celebrate small progress', next:'c2-s6', delta:{humor:2,affection:1} }] },
  { id:'c2-s6', chapter:2, bg:'sankranti-street-evening', speaker:'Narrator', text:'Sankranti lights paint Kadapa lanes gold. Sugarcane bundles, kites, rangoli, cousins, and aunties everywhere. Yagnesh and Yogitha cross paths in traditional wear near a flower stall. For a second the crowd fades. Both fold hands politely, both blush, both move on before relatives create chaos. The moment stays with them for days.', choices:[{ label:'Carry this warmth into Chapter 3', next:'c3-s1', delta:{affection:3,blush:3} }] },

  // --- Chapter 3: Stress + Confession ---
  { id:'c3-s1', chapter:3, bg:'exam-classroom', speaker:'Narrator', text:'Pre-board pressure turns classrooms serious. Even laughter becomes lower volume. Yet the 10:30 break still functions like fate. Yagnesh reaches N120 door; Yogitha is already in Apex, pretending to focus on notes. Her friends still block, still tease, but the hostility now feels routine rather than war. Everyone knows this story is moving somewhere.', choices:[{ label:'Send silent good luck smile', next:'c3-s2', delta:{affection:2} },{ label:'Focus on exam and avoid looking', next:'c3-s2', delta:{logic:2,energy:1} }] },
  { id:'c3-s2', chapter:3, bg:'classroom-rain-window', speaker:'Narrator', text:'A rainy revision evening traps batches inside. Thunder shakes windowpanes; lights flicker; students trade formulas and panic. Yogitha drops a pen near the corridor threshold. Yagnesh picks it up, places it on the desk edge without speaking, and returns immediately. No drama. Her "thank you" is nearly silent, but genuine.', choices:[{ label:'Walk away before friends react', next:'c3-s3', delta:{affection:3,blush:2} }] },
  { id:'c3-s3', chapter:3, bg:'farewell-stage-decor', speaker:'Narrator', text:'Farewell day arrives with paper flowers, borrowed speakers, and too many emotions. Shirts are signed, jokes are louder than necessary, and everyone senses endings approaching. GD and Lokesh stand like security at the side corridor, giving Yagnesh one final pep talk: honest words, no pressure, no manipulation, accept whatever tone she chooses.', choices:[{ label:'Confess directly with respect', next:'c3-s4', delta:{affection:6,blush:4} },{ label:'Start by apologizing for awkward days', next:'c3-s4', delta:{logic:1,affection:5} }] },
  { id:'c3-s4', chapter:3, bg:'farewell-hall-evening', speaker:'Yogitha', text:'"I noticed everything," Yogitha says, voice trembling but steady. "The rain rides, strike day escort, the way you never crossed limits, never forced conversation. I was shy, my friends were noisy, and I needed time. I like you too." Corridor noise explodes in the distance while Yagnesh forgets how breathing works for three seconds.', choices:[{ label:'Promise patience and respect always', next:'c3-s5', delta:{affection:8,blush:6} }] },
  { id:'c3-s5', chapter:3, bg:'college-gate-sunset', speaker:'GD', text:'GD pretends to inspect bike mileage while hiding tears. Lokesh declares victory dance rights and almost slips on a puddle. Yogitha’s friends still tease but stop blocking doorways after that day. The crush chapter closes not with fireworks, but with relief, laughter, and a promise to grow slowly through 12th and beyond.', choices:[{ label:'Begin early dating phase', next:'c3-s6', delta:{humor:3,energy:2} }] },
  { id:'c3-s6', chapter:3, bg:'patha-home-night-sky', speaker:'Narrator', text:'That night, stars over Patha Kadapa look unusually clear. Yagnesh writes one line in his notebook: "No shortcuts. No disrespect. Build the future step by step." The destiny is fixed toward marriage, but the journey’s flavor now depends on daily choices, care, and consistency.', choices:[{ label:'Enter Chapter 4', next:'c4-s1', delta:{logic:2} }] },

  // --- Chapter 4: Golden Dating Era unlock ---
  { id:'c4-s1', chapter:4, bg:'new-rtc-road-evening', speaker:'Narrator', text:'Post-confession, the world map expands. New RTC Road unlocks with cinemas, fabric stores, traffic lights, and endless snack aromas. Dating is now allowed, but discreetly; strict relatives can appear anywhere. GD and Lokesh become rotating lookouts, treating each outing like a classified operation with code words and emergency diversion routes.', choices:[{ label:'Pick movie date plan', next:'c4-s2', delta:{blush:2} },{ label:'Pick bookshop and tea plan', next:'c4-s2', delta:{affection:2,logic:1} }] },
  { id:'c4-s2', chapter:4, bg:'theater-lobby', speaker:'Yogitha', text:'Inside the theater queue, Yogitha laughs at how serious the boys act. "Your team behaves like secret agents," she whispers. Yagnesh smiles and admits fear of random relatives more than exam invigilators. They share popcorn, awkward shoulder distance, and soft conversation about future studies, family expectations, and balancing dreams with tradition.', choices:[{ label:'Talk about career goals honestly', next:'c4-s3', delta:{affection:3,logic:2} },{ label:'Keep date light and playful', next:'c4-s3', delta:{humor:3,blush:1} }] },
  { id:'c4-s3', chapter:4, bg:'yv-street-food', speaker:'Narrator', text:'YV Street glows under tube lights and steam from mirchi bajji stalls. Because gifts were banned before acceptance, today feels symbolic: Yagnesh finally buys a small bangle set and asks permission before offering it. Yogitha accepts with a shy nod. The gesture is modest, thoughtful, and perfectly timed after trust has formed.', choices:[{ label:'Choose silver-blue bangles', next:'c4-s4', delta:{affection:4,blush:3} },{ label:'Choose traditional maroon set', next:'c4-s4', delta:{affection:4,logic:1} }] },
  { id:'c4-s4', chapter:4, bg:'rtc-road-crossing', speaker:'Narrator', text:'A stressful moment hits when a relative’s scooter appears near the signal. GD instantly starts a fake phone argument about bike insurance to block sightline while Lokesh drags Yagnesh toward a newspaper stand. Yogitha suppresses laughter and pretends to compare bangles with a shop aunty. Crisis passes. Everyone exhales dramatically.', choices:[{ label:'Thank team for smooth save', next:'c4-s5', delta:{humor:3,energy:-1} },{ label:'Review better contingency protocol', next:'c4-s5', delta:{logic:3} }] },
  { id:'c4-s5', chapter:4, bg:'college-campus-return', speaker:'Narrator', text:'Back at campus routines, their interactions remain subtle. No overacting, no public drama, only steady signals. Friends still tease; stress still appears around marks and family calls; yet each day ends calmer than it begins. This is not cinematic perfection. It is patient, imperfect, decent love learning to survive real life.', choices:[{ label:'Advance relationship with consistency', next:'c4-s6', delta:{affection:3,energy:1} }] },
  { id:'c4-s6', chapter:4, bg:'sunset-lake-kadapa', speaker:'Narrator', text:'At sunset by the lake, they discuss boundaries and future timelines. Yogitha says she values safety, respect, and honesty over flashy gestures. Yagnesh agrees. The affection bar climbs not from grand speeches, but from repeated good behavior under pressure. That math will define everything after graduation.', choices:[{ label:'Enter Chapter 5 wedding preparations', next:'c5-s1', delta:{affection:3,logic:2} }] },

  // --- Chapter 5: Wedding Build + Mini-games ---
  { id:'c5-s1', chapter:5, bg:'family-meeting-home', speaker:'Narrator', text:'Years roll forward through studies and family discussions. Eventually both homes agree. Patha Kadapa buzzes with preparation lists, sari selections, invitation disputes, and endless tea rounds. GD claims he should be compensated for historic petrol usage. Lokesh volunteers for logistics and mostly eats laddus. The mandapam date is fixed; excitement turns beautifully serious.', choices:[{ label:'Help with planning spreadsheet', next:'c5-s2', delta:{logic:3} },{ label:'Help with decoration and music picks', next:'c5-s2', delta:{humor:2,affection:2} }] },
  { id:'c5-s2', chapter:5, bg:'pelli-mandapam-prep', speaker:'Narrator', text:'Wedding hall transforms into marigold gold, silk red, and brass-lamp warmth. Nadaswaram rehearsals echo under ceiling fans. Yogitha enters in traditional elegance that silences even Lokesh for a full five seconds. Yagnesh feels the same corridor-shy nervousness from school days, only now layered with gratitude and responsibility.', choices:[{ label:'Center yourself before ritual', next:'c5-s3', delta:{energy:2,blush:2} }] },
  { id:'c5-s3', chapter:5, bg:'pelli-stage-ritual', speaker:'Narrator', text:'Priests call for Jeelakarra Bellam. Timing matters, eye contact matters, and hands tremble slightly under hundreds of watching relatives. This is where playful mini-game precision meets sacred emotion. The hall quiets; flute and nadaswaram hold one long note.', choices:[{ label:'Start Jeelakarra Bellam mini-game', next:'mg-jeelakarra', miniGame:'jeelakarra' }] },
  { id:'c5-s4', chapter:5, bg:'pelli-stage-bright', speaker:'Narrator', text:'The ritual lands beautifully. Cheers rise, cameras flash, and both families visibly relax. GD wipes his eye and insists it is only smoke from camphor. Priests move to Talambralu. Rice bowls are ready, cousins are ready, and playful chaos is about to begin.', choices:[{ label:'Start Talambralu mini-game', next:'mg-talambralu', miniGame:'talambralu' }] },
  { id:'c5-s5', chapter:5, bg:'pelli-stage-laughter', speaker:'Yogitha', text:'Rice showers sparkle under stage lights as Yogitha laughs without restraint. "From blocked corridors to this mandapam," she says softly, "we took the long route, but it was the right route." Yagnesh ties the knot with steady hands. Affection surges; blush meter also spikes despite everyone watching.', choices:[{ label:'Receive blessings and continue', next:'c5-s6', delta:{affection:10,blush:7,energy:2} }] },
  { id:'c5-s6', chapter:5, bg:'wedding-night-courtyard', speaker:'Narrator', text:'After ceremonies, the courtyard quiets. Flower petals on stone floor, distant traffic, tired smiles, full hearts. The marriage chapter completes exactly as destiny demanded: no failure branches, only tonal differences based on choices. Tomorrow begins ordinary life, the hardest and most meaningful arc of all.', choices:[{ label:'Begin married life Chapter 6', next:'c6-s1', delta:{logic:2} }] },

  // --- Chapter 6: Early Married Life ---
  { id:'c6-s1', chapter:6, bg:'new-home-morning', speaker:'Narrator', text:'Married mornings start with chai, grocery lists, and playful arguments about alarm timing. Romance now includes practical teamwork: bills, travel planning, elder care calls, and meal prep after long workdays. The atmosphere is warm but real; stress appears in small waves. Both choose conversation over ego, and that keeps the house peaceful.', choices:[{ label:'Prioritize shared routines', next:'c6-s2', delta:{affection:3,logic:2} },{ label:'Prioritize spontaneity and outings', next:'c6-s2', delta:{humor:3,energy:1} }] },
  { id:'c6-s2', chapter:6, bg:'market-road-day', speaker:'Narrator', text:'On busy market roads, they relearn old auto-follow humor from the opposite side: now they are the couple being observed by friends. GD still roasts Yagnesh for wasting petrol in school days. Yogitha counters with stories of how obvious he was during rainy breaks. Even stressful errands turn into light comedy.', choices:[{ label:'Laugh and keep shopping', next:'c6-s3', delta:{humor:3,affection:2} }] },
  { id:'c6-s3', chapter:6, bg:'gd-house-reunion', speaker:'Lokesh', text:'At GD’s house reunion, walls are decorated with mock mission posters: "Operation Line-of-Sight," "Strike Day Convoy," and "Rainy Day Survival." Everyone laughs until power cuts suddenly during dinner. In darkness, old anxieties surface briefly. They handle it with lantern light, jokes, and calm teamwork, proving growth under inconvenience.', choices:[{ label:'Stabilize mood with humor', next:'c6-s4', delta:{humor:2,energy:1} },{ label:'Stabilize mood with planning', next:'c6-s4', delta:{logic:2} }] },
  { id:'c6-s4', chapter:6, bg:'rainy-balcony-night', speaker:'Yogitha', text:'Rain returns on their balcony, recalling school-day bike chases. "Back then I smiled from the auto," Yogitha says. "Now I worry if you forget your raincoat." The sentence sounds simple but lands deeply. Care has evolved from curiosity into partnership. Affection climbs in quiet, domestic scenes more than dramatic events.', choices:[{ label:'Promise to take care better', next:'c6-s5', delta:{affection:4,blush:2} }] },
  { id:'c6-s5', chapter:6, bg:'city-temple-evening', speaker:'Narrator', text:'They visit a temple fair where old classmates appear unexpectedly. Friendly teasing returns; stories get exaggerated; everyone claims partial credit for the love story. A few complex moments appear when comparing life progress, but Yagnesh and Yogitha ground each other. They leave with prasad, laughter, and a stronger sense of shared direction.', choices:[{ label:'Step into long-arc growth', next:'c6-s6', delta:{energy:2,logic:1} }] },
  { id:'c6-s6', chapter:6, bg:'moonlit-road-home', speaker:'Narrator', text:'Driving home under sodium lights, they agree on a simple principle: keep dignity during conflict, keep fun during stress, and keep gratitude during routine. That formula becomes the hidden engine behind the next chapters and explains why destiny remains stable despite changing life pressures.', choices:[{ label:'Enter Chapter 7 expansion', next:'c7-s1', delta:{affection:2} }] },

  // --- Chapter 7: Complex Middle Arc ---
  { id:'c7-s1', chapter:7, bg:'office-college-split', speaker:'Narrator', text:'This chapter blends responsibility and nostalgia. Work deadlines, family visits, and social obligations compress time. One week feels particularly tense when schedules clash and both become quieter than usual. No meltdown, no melodrama, just two tired people learning to communicate before misunderstanding hardens into distance.', choices:[{ label:'Initiate calm conversation early', next:'c7-s2', delta:{logic:3,affection:2} },{ label:'Give space, then reconnect at night', next:'c7-s2', delta:{energy:2,blush:1} }] },
  { id:'c7-s2', chapter:7, bg:'living-room-night', speaker:'Yagnesh', text:'Yagnesh admits he sometimes overthinks silence. Yogitha admits she sometimes carries stress quietly to avoid burdening others. They negotiate better check-in rituals: one message at lunch, one evening walk, one weekly no-phone hour. It sounds small, but these systems prevent future friction better than emotional speeches.', choices:[{ label:'Adopt communication routine', next:'c7-s3', delta:{logic:3,affection:3} }] },
  { id:'c7-s3', chapter:7, bg:'park-evening-walk', speaker:'Narrator', text:'During evening walk, they meet Yogitha’s former friends. The same girls who once blocked corridors now smile and joke, "Bodyguard project ended successfully." There is playful embarrassment, lingering memories, and genuine reconciliation. Complex emotions resolve into mutual respect, proving people can evolve beyond first impressions.', choices:[{ label:'Accept teasing gracefully', next:'c7-s4', delta:{humor:3,blush:2} }] },
  { id:'c7-s4', chapter:7, bg:'highway-rain-stop', speaker:'Narrator', text:'On a weekend drive, sudden rain forces a stop near an old bus shelter. The scene mirrors Chapter 2 but with reversed roles: Yogitha lectures road safety while GD, on a call, shouts from speaker mode about tire pressure. Stress turns comic again. Shared history transforms bad weather into affectionate nostalgia.', choices:[{ label:'Take shelter and laugh', next:'c7-s5', delta:{affection:3,humor:2} },{ label:'Analyze route and continue carefully', next:'c7-s5', delta:{logic:2,energy:1} }] },
  { id:'c7-s5', chapter:7, bg:'family-dinner-hall', speaker:'Narrator', text:'A family dinner introduces complicated logistics: elders discussing relocations, finances, responsibilities, and future planning. The tone is serious but not bleak. Yagnesh and Yogitha answer together, balancing ambition with tradition. The chapter proves maturity: love is now both emotional and administrative competence.', choices:[{ label:'Close chapter with united decision', next:'c7-s6', delta:{logic:3,affection:2} }] },
  { id:'c7-s6', chapter:7, bg:'rooftop-stars', speaker:'Narrator', text:'Under rooftop stars, they review the day and appreciate how far they came from corridor silence. The blush meter still reacts to simple compliments; affection rises with every solved problem. Destiny path remains fixed to happiness, but effort determines elegance. They choose elegance.', choices:[{ label:'Move to Chapter 8 celebrations', next:'c8-s1', delta:{affection:2,blush:2} }] },

  // --- Chapter 8: Festivals and Joy ---
  { id:'c8-s1', chapter:8, bg:'sankranti-home-colorful', speaker:'Narrator', text:'Sankranti returns with full color in their own home: rangoli spirals, mango leaves, sugarcane, cousins running through doorways, and elders offering advice nobody requested. This time there is no hiding, no corridor blocks, no uncertainty. They host together, efficient and affectionate, while GD critiques kite aerodynamics like a professor.', choices:[{ label:'Host with playful energy', next:'c8-s2', delta:{energy:3,humor:2} },{ label:'Host with precise planning', next:'c8-s2', delta:{logic:3} }] },
  { id:'c8-s2', chapter:8, bg:'shanthi-nagar-visit', speaker:'Yogitha', text:'Visiting Shanthi Nagar relatives brings old nervousness, but now it converts into confidence. Yogitha introduces Yagnesh proudly. A few aunties test him with rapid questions about work, habits, and future goals. He answers honestly, with respect and occasional humor. Approval arrives slowly, then all at once over sweet pongal.', choices:[{ label:'Stay humble and warm', next:'c8-s3', delta:{affection:4,blush:1} }] },
  { id:'c8-s3', chapter:8, bg:'college-memory-day', speaker:'Narrator', text:'They revisit Narayana campus during a community event. Corridors look smaller now. N120 and Apex doorways still face each other like old rivals, but the tension is gone. They stand where everything started and smile at their younger selves—awkward, sincere, and unexpectedly brave.', choices:[{ label:'Recreate 10:30 pose for photo', next:'c8-s4', delta:{blush:3,humor:2} },{ label:'Take quiet gratitude moment', next:'c8-s4', delta:{affection:3,logic:1} }] },
  { id:'c8-s4', chapter:8, bg:'yv-street-night-food', speaker:'Narrator', text:'Night at YV Street becomes a celebration montage: pani puri challenge, roasted corn, shared kulfi, and friendly arguments about spice tolerance. Small stress appears when a work call interrupts, but they pause, handle it quickly, and return to laughter. Emotional flexibility becomes a visible skill now.', choices:[{ label:'Finish night with tea and talk', next:'c8-s5', delta:{energy:2,affection:2} }] },
  { id:'c8-s5', chapter:8, bg:'gd-house-poster-wall', speaker:'GD', text:'GD unveils a framed chart titled "Destiny Proof v3.0" with absurd equations: Respect^Consistency + Humor/Stress = Stable Marriage. Everyone laughs, then admits the math is emotionally accurate. Lokesh signs the bottom as "Field Research Specialist." The bar meters rise because joy plus friendship is also romance infrastructure.', choices:[{ label:'Archive the legendary chart', next:'c8-s6', delta:{humor:3,logic:1} }] },
  { id:'c8-s6', chapter:8, bg:'home-lantern-night', speaker:'Narrator', text:'Lanterns glow outside as chapter closes. Affection nears high cap; blush remains lively; energy stabilizes through better routines. The story tone is now predominantly happy, with complexity handled through communication. Final chapters will focus on legacy, reaffirmation, and final debug confirmation.', choices:[{ label:'Proceed to Chapter 9', next:'c9-s1', delta:{affection:2} }] },

  // --- Chapter 9: Legacy Memories ---
  { id:'c9-s1', chapter:9, bg:'photo-album-room', speaker:'Narrator', text:'Sorting old photos triggers a memory avalanche: rain rides, strike escort, festival crossings, farewell confession, wedding rituals, first home groceries. They laugh at bad hairstyles, dramatic poses, and GD’s impossible seriousness. Nostalgia is sweet but also clarifying—it reveals how many tiny decent choices built this life.', choices:[{ label:'Rewatch memories together', next:'c9-s2', delta:{affection:3,blush:2} }] },
  { id:'c9-s2', chapter:9, bg:'college-gate-evening', speaker:'Yogitha', text:'At the old college gate, Yogitha says, "You never pushed beyond my comfort. That is why I trusted you." The line lands as a core theorem of the story. Respect was not decorative; it was structural. Destiny may be fixed, but dignity decided the quality of every chapter.', choices:[{ label:'Thank her for saying it', next:'c9-s3', delta:{affection:5,blush:2} }] },
  { id:'c9-s3', chapter:9, bg:'auto-stand-sunset', speaker:'Narrator', text:'An auto horn passes and both burst into instant laughter. Symbol loops complete: what was once nervous surveillance is now shared comedy. They buy tea near the stand, greet the driver who remembers nothing dramatic, and continue walking under orange sky and fluttering banners.', choices:[{ label:'Carry nostalgia into future planning', next:'c9-s4', delta:{humor:3,energy:1} }] },
  { id:'c9-s4', chapter:9, bg:'financial-planning-desk', speaker:'Narrator', text:'Evening shifts to practical planning—savings, travel goals, helping parents, and long-term home upgrades. Complex but calm. They disagree on timeline details, then resolve via spreadsheet plus chai method. Mature love looks like this: serious discussions without disrespect, compromise without resentment.', choices:[{ label:'Choose balanced budget path', next:'c9-s5', delta:{logic:4,affection:2} },{ label:'Choose experience-first path', next:'c9-s5', delta:{energy:2,humor:2} }] },
  { id:'c9-s5', chapter:9, bg:'tree-lined-road-morning', speaker:'Narrator', text:'Morning scooter ride through tree-lined roads feels cinematic: sky bright, bushes trimmed, buildings waking, school children crossing carefully. The environment itself reflects growth—familiar places now seen with calmer eyes. Their conversations are lighter because foundational trust no longer needs constant proof.', choices:[{ label:'Advance to reaffirmation arc', next:'c9-s6', delta:{affection:2,blush:1} }] },
  { id:'c9-s6', chapter:9, bg:'sunset-terrace-tea', speaker:'Narrator', text:'With terrace tea at sunset, they decide to renew vows on their anniversary in a smaller, intimate ceremony. Not out of insecurity, but gratitude. The coming chapters will intentionally celebrate what was already won.', choices:[{ label:'Enter Chapter 10', next:'c10-s1', delta:{logic:1} }] },

  // --- Chapter 10: Recalibration and near-cap stats ---
  { id:'c10-s1', chapter:10, bg:'anniversary-prep-room', speaker:'Narrator', text:'Anniversary prep begins with invitation lists, music selection, and seating debates that escalate comically. GD wants a projector timeline; Lokesh wants dance entry smoke effects. Yogitha wants elegance. Yagnesh wants everyone to stop arguing over font size. The planning is chaotic but affectionate.', choices:[{ label:'Prioritize elegant ceremony', next:'c10-s2', delta:{logic:2,affection:2} },{ label:'Allow fun chaos with limits', next:'c10-s2', delta:{humor:3} }] },
  { id:'c10-s2', chapter:10, bg:'boutique-traditional', speaker:'Yogitha', text:'Outfit trial day brings shy smiles and cinematic mirrors. Yogitha’s look is graceful, rooted, and radiant. Yagnesh’s look improves dramatically after three failed color choices and one blunt GD lecture. They joke, click photos, and notice how blush still appears like chapter-one reflex even after years together.', choices:[{ label:'Compliment sincerely', next:'c10-s3', delta:{blush:4,affection:3} }] },
  { id:'c10-s3', chapter:10, bg:'city-road-nightlights', speaker:'Narrator', text:'A late-night drive through lit roads becomes unexpectedly emotional. They pass old tuition buildings, bus stops, and the lane where strike-day escort happened. Stress from current responsibilities fades into appreciation for shared endurance. Affection crosses the 90+ zone for most paths here, mathematically trending toward full cap.', choices:[{ label:'Acknowledge journey openly', next:'c10-s4', delta:{affection:5,energy:1} }] },
  { id:'c10-s4', chapter:10, bg:'hall-rehearsal-stage', speaker:'Narrator', text:'Rehearsal day reveals minor conflicts about timing and relatives arriving late. Instead of snapping, both use their communication protocol: pause, clarify, decide, move on. Complex moment resolved in under ten minutes. This is the matured version of the couple who once relied on corridor glances.', choices:[{ label:'Lock final event plan', next:'c10-s5', delta:{logic:3,affection:2} }] },
  { id:'c10-s5', chapter:10, bg:'anniversary-lights', speaker:'Narrator', text:'Ceremony night glows with warm lights, jasmine, veena interludes, and low laughter. Speeches are short, heartfelt, and occasionally hilarious. By chapter-end, affection is expected to cap on most playthroughs; blush usually caps by late Chapter 10 or early Chapter 11 depending on choices.', choices:[{ label:'Proceed to Chapter 11 finale build', next:'c10-s6', delta:{affection:4,blush:3} }] },
  { id:'c10-s6', chapter:10, bg:'home-quiet-midnight', speaker:'Narrator', text:'After guests leave, silence feels rich instead of lonely. They sit among folded chairs and leftover flowers, exhausted and content. The next chapter will formalize what stats already imply: destiny succeeded, and quality remained beautiful.', choices:[{ label:'Enter Chapter 11', next:'c11-s1', delta:{energy:2} }] },

  // --- Chapter 11: Celebration and cap ---
  { id:'c11-s1', chapter:11, bg:'pelli-stage-recreated', speaker:'Narrator', text:'Chapter 11 recreates wedding aesthetics in a softer, more intimate style: marigold drapes, brass lamps, pastel silk, flute-led soundtrack. Friends and family gather not for obligation but for joy. The mood is playful, sentimental, and deeply stable—exactly the tone promised by Destiny-Fixed design.', choices:[{ label:'Open with gratitude speech', next:'c11-s2', delta:{affection:3,logic:1} },{ label:'Open with humorous story montage', next:'c11-s2', delta:{humor:3,blush:1} }] },
  { id:'c11-s2', chapter:11, bg:'vow-stage-close', speaker:'Yagnesh', text:'Yagnesh thanks Yogitha for choosing patience over noise and trust over fear. He thanks GD and Lokesh for comic support and practical logistics across years. Yogitha smiles with visible blush, proving some emotions never desaturate. Audience applause is warm, not loud—like family weather.', choices:[{ label:'Exchange vows again', next:'c11-s3', delta:{affection:4,blush:3} }] },
  { id:'c11-s3', chapter:11, bg:'vow-stage-close', speaker:'Yogitha', text:'"Destiny gave us the ending," Yogitha says. "But we chose the style—funny, respectful, stubborn, and kind." That line typically pushes blush to full cap if not already maxed. Affection is usually full by this point on every branch due to cumulative positive deltas and no failure states.', choices:[{ label:'Seal celebration with ring exchange', next:'c11-s4', delta:{affection:5,blush:4} }] },
  { id:'c11-s4', chapter:11, bg:'dance-floor-family', speaker:'Narrator', text:'Dance sequence follows: cousins overperform, GD forgets steps, Lokesh invents steps, elders clap in rhythm. Lighthearted chaos restores energy after emotional speeches. Stress is absent, replaced by completion and belonging. This is a happy-ending system executing exactly as intended.', choices:[{ label:'Move toward final audit chapter', next:'c11-s5', delta:{energy:3,humor:2} }] },
  { id:'c11-s5', chapter:11, bg:'night-garden-lights', speaker:'Narrator', text:'In a garden corner, the couple shares ten quiet minutes away from cameras. They review old fear points—exams, relatives, misunderstandings—and appreciate how each was solved without breaking respect. The game’s logic has been validated by lived scenes, not merely debug text.', choices:[{ label:'Unlock final chapter', next:'c11-s6', delta:{affection:2,logic:2} }] },
  { id:'c11-s6', chapter:11, bg:'chapter-gate-light', speaker:'Narrator', text:'Chapter 12 unlocks with meters near or at maximum and a stable emotional baseline. Final section will run explicit system audit of affection/blush fill points, branch convergence, and Destiny-Fixed guarantees.', choices:[{ label:'Enter Chapter 12 audit + finale', next:'c12-s1' }] },

  // --- Chapter 12: Final Debug + Ending ---
  { id:'c12-s1', chapter:12, bg:'finale-skyline-dawn', speaker:'Narrator', text:'Grand finale dawn over Kadapa skyline: rooftops, trees, temple gopuram silhouette, and waking roads. Story arcs converge—11th crush, 12th confession, dating era, wedding rituals, and post-marriage growth. You now run formal narrative audit before ending screen.', choices:[{ label:'Run affection progression audit', next:'c12-s2', delta:{logic:2} }] },
  { id:'c12-s2', chapter:12, bg:'debug-console-theme', speaker:'Narrator', text:'AFFECTION AUDIT: Typical full-cap window is Chapter 10 Scene 5 through Chapter 11 Scene 3, depending on humor/logic branch choices. Early high-affection routes may cap in late Chapter 9. No branch includes affection collapse events; penalties only affect pace, never outcome.', choices:[{ label:'Run blush progression audit', next:'c12-s3', delta:{logic:2} }] },
  { id:'c12-s3', chapter:12, bg:'debug-console-theme', speaker:'Narrator', text:'BLUSH AUDIT: Blush surges in Chapter 3 confession, Chapter 5 rituals, and Chapter 10 outfit/drive sequences. Designed full-cap window is late Chapter 10 to Chapter 11 Scene 3. All branches preserve recurring shy beats so blush remains narratively consistent even after marriage.', choices:[{ label:'Run destiny convergence audit', next:'c12-s4', delta:{logic:2} }] },
  { id:'c12-s4', chapter:12, bg:'debug-console-theme', speaker:'Narrator', text:'DESTINY-FIXED AUDIT: Every decision tree is flavor-only (funny, smooth, awkward, practical). Branches converge on stable checkpoints. There are no breakup nodes, no dead ends, and no failure endings. Stress scenes modify tone and stat pacing but always return to happy trajectory.', choices:[{ label:'Run mini-game logic audit', next:'c12-s5', delta:{logic:2} }] },
  { id:'c12-s5', chapter:12, bg:'debug-console-theme', speaker:'Narrator', text:'MINI-GAME AUDIT: Shadow Follow influences early trust flavor; Jeelakarra and Talambralu amplify wedding joy. Win/loss outcomes affect stat bonuses and humor, never destiny path. Input handling, timing windows, and autosave transitions are validated at mini-game exit.', choices:[{ label:'Finalize ending with gratitude', next:'c12-s6', delta:{affection:6,blush:6,energy:3} }] },
  { id:'c12-s6', chapter:12, bg:'finale-mandapam-sunrise', speaker:'Narrator', text:'Final scene: Yagnesh and Yogitha stand beneath morning light, surrounded by friends, family, and the city that watched their journey. The story remains gradual, humorous, shy, stressed at times, complex when needed, and always hopeful. Destiny is fulfilled. Love is not rushed. Happiness is earned and sustained.', choices:[{ label:'View final ending stats', next:null }] },

  // mini-game nodes
  { id:'mg-follow-1', chapter:2, bg:'college-evening-gate', speaker:'Narrator', text:'Mini-game node.', miniGame:'shadow-follow', choices:[] },
  { id:'mg-jeelakarra', chapter:5, bg:'pelli-stage-ritual', speaker:'Narrator', text:'Mini-game node.', miniGame:'jeelakarra', choices:[] },
  { id:'mg-talambralu', chapter:5, bg:'pelli-stage-bright', speaker:'Narrator', text:'Mini-game node.', miniGame:'talambralu', choices:[] }
];
